# Setup
title:        Electron React Todo
tagline:      A simple todo application implemented in React, Redux and Electron
baseurl:      "/electron-react-todo"
paginate:     1

# About/contact
author:
  name:       Subeesh
  url:        https://github.com/subeesh/electron-react-todo

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
