# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/electron-react-todo"
paginate:     1

# About/contact
author:
  name:       Subeesh
  url:        https://github.com/subeesh/electron-react-todo

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
